### ISSUE TITLE
Different dataset

### ISSUE THREAD

**Issue by drewgash** [bartchr808/EmotionPredictingCNN#2]
Hey Bart,

Me again, ideas on how I would go about implementing something similar with the KTH Dataset?

**Comment by bartchr808** [comment]
Hey Andrew,

I've been busy with work currently and unable to help you much here. Additionally, Github issues aren't meant for help with trying to get it working in another project. They are meant for issues regarding it erroring, not training correctly, etc.

**Comment by bartchr808** [comment]
Closed since this isn't an issue regarding the project
